/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Rishni, Sewmi
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
   
        
//        jFacultyButton.setBackground(new Color(0, 0, 0, 0));
//        jFacultyButton.setOpaque(false);
//        
//        
//        
//        al = new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                   FacultyMain fm = new FacultyMain();
//                   jDesktopPane1.add(fm);
//                
//            }
//
//        };
//        
//        tm = new Timer(100, al);
//        tm2 = new Timer(100, al2);
////        jDesktopPane1.removeAll();
////        MainInternalAdmin mia= new MainInternalAdmin();
////        jDesktopPane1.add(mia).setVisible(true);
    }
    
    public void facultyMainOpen()
    {
//        jDesktopPane1.removeAll();
//        FacultyMain fm=new FacultyMain();
//        jDesktopPane1.add(fm).setVisible(true);
    }

//    public javax.swing.JDesktopPane getDesktopPane()
//    {
////        return jDesktopPane1;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFacultyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_ViewFaculty = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_MainStudent = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCourseButton1 = new javax.swing.JButton();
        btn_ViewProfile = new javax.swing.JButton();
        btn_ViewFaculty1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jFacultyButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jFacultyButton.setText("Faculty");
        jFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFacultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jFacultyButton);
        jFacultyButton.setBounds(20, 370, 280, 80);

        jLabel1.setText("pic");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 14);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student Management System Home Panels");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 460, 30);

        btn_ViewFaculty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_ViewFaculty.setText("View Courses");
        getContentPane().add(btn_ViewFaculty);
        btn_ViewFaculty.setBounds(380, 290, 280, 80);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 510, 65, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 330, 80);

        btn_MainStudent.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_MainStudent.setText("Student Details (Add/ Delete/ Update/ Search)");
        btn_MainStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MainStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MainStudent);
        btn_MainStudent.setBounds(20, 290, 280, 80);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setText("Exam");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 210, 280, 80);

        jCourseButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCourseButton1.setText("Course");
        getContentPane().add(jCourseButton1);
        jCourseButton1.setBounds(20, 130, 280, 80);

        btn_ViewProfile.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_ViewProfile.setText("View My Profile");
        getContentPane().add(btn_ViewProfile);
        btn_ViewProfile.setBounds(380, 130, 280, 80);

        btn_ViewFaculty1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_ViewFaculty1.setText("View Faculty");
        getContentPane().add(btn_ViewFaculty1);
        btn_ViewFaculty1.setBounds(380, 210, 280, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFacultyButtonActionPerformed
        // tm.start();
        this.dispose();
        Faculty faculty;
        try {
            faculty = new Faculty();
            faculty.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jFacultyButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Login logOut = new Login();
        logOut.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    private void btn_MainStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MainStudentActionPerformed
        this.dispose();
        Student stu;
        stu = new Student();
        stu.setVisible(true);
    }//GEN-LAST:event_btn_MainStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_MainStudent;
    private javax.swing.JButton btn_ViewFaculty;
    private javax.swing.JButton btn_ViewFaculty1;
    public javax.swing.JButton btn_ViewProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jCourseButton1;
    private javax.swing.JButton jFacultyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
